server:
  port: 8080
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://140.238.6.16:3306/testdb
    username: synergyuser
    password: synergy1234
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.synergies.synergy.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    jdbc:
      sqlonly: off
      sqltiming: info
      resultsettable: info
      audit: off
      resultset: off
      connection: off