spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/testdb
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.synergies.synergy.domain